trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Docker/*

variables:
  - group: Docker-Credentials
  - name: DOCKER_TAG
    value: '$(Build.BuildId)' 
  - name: DOCKER_FILEPATH
    value: '$(Build.SourcesDirectory)/Docker/Dockerfile'
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push stage
  pool:
    vmImage: $(vmImageName)
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 20.10.24
        releaseType: stable
  
    - task: CmdLine@2
      displayName: Execute Docker Build and Push
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/Docker'
        script: |
          set -euo pipefail
          sh docker_build.sh
      env:
        DOCKER_TAG: $(DOCKER_TAG)
        DOCKER_USERNAME: $(DOCKER_USERNAME)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)
        DOCKER_IMAGEREPO: $DOCKER_IMAGEREPO
        DOCKER_FILE_PATH: $(DOCKER_FILEPATH)

- stage: Deploy
  displayName: Create PR for Turo repo
  pool:
    vmImage: $(vmImageName)
  jobs:
  - job: UpdateTerraform
    displayName: Update Image Tag in Terraform
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
     
    - task: CmdLine@2
      displayName: Create and publish branch
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/terraform'
        script: |
          git config --global user.email "nishilampally25@gmail.com"
          git config --global user.name "Nishil Ampally"
          BRANCH_NAME="feature-build-$(Build.BuildId)"
          echo $BRANCH_NAME
          git fetch origin main
          git checkout -b $BRANCH_NAME origin/main
          sed -i "s/^tag\s*=.*/tag = \"$(Build.BuildId)\"/" terraform.tfvars
          terraform fmt .
          git add .
          git commit -m "Updated Docker image tag [skip ci]"
          git push -u origin $BRANCH_NAME

   # Below  task creates PR in Azure DevOps

    # - task: CmdLine@2
    #   displayName: Create Pull Request
    #   inputs:
    #     script: |
    #       echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    #       az devops configure --defaults organization=nikhithaampally project=Turo Assignment --use-git-aliases true
    #       az repos pr create -d "Updated Docker tag $(Build.BuildId)" -t main -s feature-build-$(Build.BuildId) --description "This is an automated PR." --delete-source-branch -r TURO
    #   env:
    #     AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)

     # Below code creates PR in GITHUB   
        
    - task: CmdLine@2
      displayName: 'Create Pull Request'
      inputs:
        script: |
          curl -X POST \
          -H "Authorization: token $(GITHUB_TOKEN)" \
          -H "Content-Type: application/json" \
          -d '{
            "title": "Updated Docker tag $(Build.BuildId)",
            "head": "feature-build-$(Build.BuildId)",
            "base": "main",

            "body": "Updated Docker tag to $(Build.BuildId)"
          }' "https://api.github.com/repos/nishilampally/turoassignment/pulls"
        